root|phosphor-run|1|Phosphor Run
root|rosey-chop|1|Rosey Chop
root|settings|1|Settings
root|power|1|Power Down
settings|input|1|Input Settings
settings|display|1|Display Area
settings|hardware|1|Hardware Test
