"""Build the fixed-size launcher mascot and Fredoka masks. Requires Pillow 12.3.0."""
from pathlib import Path
import argparse
import hashlib
import json
import tempfile
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "assets/launcher"
OUTPUTS = ["assets/launcher/mascot.png", "assets/launcher/mascot.ppm", "include/launcher_font.h"]
ICON_SOURCES = json.loads((ART / "icon-sources.json").read_text())
OUTPUTS += list(ICON_SOURCES["icons"]) + ["include/launcher_icons.h"]


def build_icons(destination):
    icons = {}
    for name, recipe in ICON_SOURCES["icons"].items():
        source_path = ROOT / recipe["source"]
        if source_path.suffix == ".pam":
            header, pixels = source_path.read_bytes().split(b"ENDHDR\n", 1)
            values = dict(line.split(maxsplit=1) for line in header.splitlines()[1:] if b" " in line)
            source = Image.frombytes("RGBA", (int(values[b"WIDTH"]), int(values[b"HEIGHT"])), pixels)
        else:
            source = Image.open(source_path).convert("RGBA")
        # Native-size picture details: crop only, never resize runtime artwork.
        icon = source.crop(recipe["crop"])
        assert icon.size == tuple(ICON_SOURCES["cell"])
        target = destination / name
        target.parent.mkdir(parents=True, exist_ok=True)
        icon.save(target)
        icons[name] = icon
    entries = []
    for manifest in sorted((ROOT / "games").glob("*/game.conf")):
        values = dict(line.split("=", 1) for line in manifest.read_text().splitlines() if "=" in line and not line.startswith("#"))
        if "launcher_icon" not in values:
            continue
        icon = icons[values["launcher_icon"]]
        pixels = [f"0x{r:02x}{g:02x}{b:02x}{a:02x}u" for r, g, b, a in icon.get_flattened_data()]
        entries.append('{"' + values["id"] + '",{' + ','.join(pixels) + '}}')
    header = "/* Generated by tools/build-launcher-art.py. Native 20x20 picture icons. */\n#ifndef CHIRKY_LAUNCHER_ICONS_H\n#define CHIRKY_LAUNCHER_ICONS_H\n#include <stdint.h>\n"
    header += "struct launcher_icon { const char *id; uint32_t pixels[400]; };\n"
    header += "static const struct launcher_icon launcher_icons[]={\n" + ",\n".join(entries) + "\n};\n#endif\n"
    (destination / "include/launcher_icons.h").write_text(header, encoding="utf-8", newline="\n")


def build(destination):
    dest = destination / "assets/launcher"
    dest.mkdir(parents=True, exist_ok=True)
    source = Image.open(ART / "source/mascot.png").convert("RGBA")
    source = source.crop(source.getchannel("A").getbbox())
    source.thumbnail((60, 60), Image.Resampling.NEAREST)
    # Reduce exactly once to the runtime grid, with two transparent gutter pixels.
    alpha = source.getchannel("A").point(lambda a: 255 if a >= 128 else 0)
    source = source.convert("RGB").quantize(colors=48, method=Image.Quantize.MAXCOVERAGE, dither=Image.Dither.NONE).convert("RGBA")
    source.putalpha(alpha)
    cell = Image.new("RGBA", (64, 64))
    cell.paste(source, ((64-source.width)//2, 62-source.height))
    cell.save(dest / "mascot.png")
    # Runtime PPM is opaque on the shared solid navy, exactly 64x64.
    background = Image.new("RGB", cell.size, (37, 36, 51))
    background.paste(cell, mask=cell.getchannel("A"))
    background.save(dest / "mascot.ppm")
    header = ["/* Generated by tools/build-launcher-art.py; Fredoka under assets/launcher/source/OFL.txt. */",
              "#ifndef CHIRKY_LAUNCHER_FONT_H", "#define CHIRKY_LAUNCHER_FONT_H", "#include <stdint.h>"]
    advances, masks = [], []
    for size in (11, 13, 17):
        font = ImageFont.truetype(str(ART / "source/Fredoka.ttf"), size)
        widths, glyphs = [], []
        for code in range(32, 127):
            widths.append(round(font.getlength(chr(code))))
            glyph = Image.new("L", (16, 20))
            ImageDraw.Draw(glyph).text((0, 14), chr(code), font=font, anchor="ls", fill=255)
            pixels = glyph.load()
            rows = [sum(round(pixels[x, y]/85) << (x*2) for x in range(16)) for y in range(20)]
            glyphs.append("{" + ",".join(f"0x{row:08x}u" for row in rows) + "}")
        advances.append("{" + ",".join(map(str, widths)) + "}")
        masks.append("{\n" + ",\n".join(glyphs) + "\n}")
    header += ["static const unsigned char launcher_font_advance[3][95]={" + ",\n".join(advances) + "};",
               "static const uint32_t launcher_font_mask[3][95][20]={" + ",\n".join(masks) + "};", "#endif", ""]
    (destination / "include").mkdir(exist_ok=True)
    (destination / "include/launcher_font.h").write_text("\n".join(header), encoding="utf-8", newline="\n")
    build_icons(destination)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        with tempfile.TemporaryDirectory() as temporary:
            build(Path(temporary))
            for name in OUTPUTS:
                assert (ROOT / name).read_bytes() == (Path(temporary) / name).read_bytes(), name + " differs from approved output"
        print("Launcher regeneration matches approved runtime files.")
    else:
        build(ROOT)
        manifest = {"version": 1, "cell": [64, 64], "contentMax": [60, 60], "gutter": 2,
                    "baseline": Image.open(ART / "mascot.png").getchannel("A").getbbox()[3]-1,
                    "frames": ["idle"], "alpha": "binary", "paletteMax": 49,
                    "renderScale": 1, "fontSizes": [11, 13, 17], "fontCell": [16, 20],
                    "identity": "Cream CRT, smiling green eyes, red comb, red/green/blue tail, orange beak and feet",
                    "icons": ICON_SOURCES,
                    "hashes": {name: hashlib.sha256((ROOT / name).read_bytes()).hexdigest() for name in
                               OUTPUTS + ["assets/launcher/source/mascot.png", "assets/launcher/source/Fredoka.ttf", "assets/launcher/icon-sources.json"] + [recipe["source"] for recipe in ICON_SOURCES["icons"].values()]}}
        (ART / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
