"""Build the fixed-size launcher mascot and Fredoka masks. Requires Pillow 12.3.0."""
from pathlib import Path
import argparse
import hashlib
import json
import tempfile
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "assets/launcher"
OUTPUTS = ["assets/launcher/mascot.png", "assets/launcher/mascot.ppm", "include/launcher_font.h"]


def build(destination):
    dest = destination / "assets/launcher"
    dest.mkdir(parents=True, exist_ok=True)
    source = Image.open(ART / "source/mascot.png").convert("RGBA")
    source = source.crop(source.getchannel("A").getbbox())
    source.thumbnail((60, 60), Image.Resampling.NEAREST)
    # Reduce exactly once to the runtime grid, with two transparent gutter pixels.
    alpha = source.getchannel("A").point(lambda a: 255 if a >= 128 else 0)
    source = source.convert("RGB").quantize(colors=48, method=Image.Quantize.MAXCOVERAGE, dither=Image.Dither.NONE).convert("RGBA")
    source.putalpha(alpha)
    cell = Image.new("RGBA", (64, 64))
    cell.paste(source, ((64-source.width)//2, 62-source.height))
    cell.save(dest / "mascot.png")
    # Runtime PPM is opaque on the shared solid navy, exactly 64x64.
    background = Image.new("RGB", cell.size, (37, 36, 51))
    background.paste(cell, mask=cell.getchannel("A"))
    background.save(dest / "mascot.ppm")
    header = ["/* Generated by tools/build-launcher-art.py; Fredoka under assets/launcher/source/OFL.txt. */",
              "#ifndef CHIRKY_LAUNCHER_FONT_H", "#define CHIRKY_LAUNCHER_FONT_H", "#include <stdint.h>"]
    advances, masks = [], []
    for size in (11, 13, 17):
        font = ImageFont.truetype(str(ART / "source/Fredoka.ttf"), size)
        widths, glyphs = [], []
        for code in range(32, 127):
            widths.append(round(font.getlength(chr(code))))
            glyph = Image.new("L", (16, 20))
            ImageDraw.Draw(glyph).text((0, 14), chr(code), font=font, anchor="ls", fill=255)
            pixels = glyph.load()
            rows = [sum(round(pixels[x, y]/85) << (x*2) for x in range(16)) for y in range(20)]
            glyphs.append("{" + ",".join(f"0x{row:08x}u" for row in rows) + "}")
        advances.append("{" + ",".join(map(str, widths)) + "}")
        masks.append("{\n" + ",\n".join(glyphs) + "\n}")
    header += ["static const unsigned char launcher_font_advance[3][95]={" + ",\n".join(advances) + "};",
               "static const uint32_t launcher_font_mask[3][95][20]={" + ",\n".join(masks) + "};", "#endif", ""]
    (destination / "include").mkdir(exist_ok=True)
    (destination / "include/launcher_font.h").write_text("\n".join(header), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        with tempfile.TemporaryDirectory() as temporary:
            build(Path(temporary))
            for name in OUTPUTS:
                assert (ROOT / name).read_bytes() == (Path(temporary) / name).read_bytes(), name + " differs from approved output"
        print("Launcher regeneration matches approved runtime files.")
    else:
        build(ROOT)
        manifest = {"version": 1, "cell": [64, 64], "contentMax": [60, 60], "gutter": 2,
                    "baseline": Image.open(ART / "mascot.png").getchannel("A").getbbox()[3]-1,
                    "frames": ["idle"], "alpha": "binary", "paletteMax": 49,
                    "renderScale": 1, "fontSizes": [11, 13, 17], "fontCell": [16, 20],
                    "identity": "Cream CRT, smiling green eyes, red comb, red/green/blue tail, orange beak and feet",
                    "hashes": {name: hashlib.sha256((ROOT / name).read_bytes()).hexdigest() for name in
                               OUTPUTS + ["assets/launcher/source/mascot.png", "assets/launcher/source/Fredoka.ttf"]}}
        (ART / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
