#ifndef CHIRKY_VIEWPORT_H
#define CHIRKY_VIEWPORT_H

enum {
    CHIRKY_FRAMEBUFFER_WIDTH = 320,
    CHIRKY_FRAMEBUFFER_HEIGHT = 240,
    CHIRKY_SAFE_X = 16,
    CHIRKY_SAFE_Y = 12,
    CHIRKY_VIEWPORT_WIDTH = CHIRKY_FRAMEBUFFER_WIDTH - CHIRKY_SAFE_X * 2,
    CHIRKY_VIEWPORT_HEIGHT = CHIRKY_FRAMEBUFFER_HEIGHT - CHIRKY_SAFE_Y * 2
};

#endif
